# Generated by Django 4.1.6 on 2023-02-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='sub_total',
        ),
    ]
